### ISSUE TITLE
Doubt on mechanism of updating popluation

### ISSUE THREAD

**Issue by Vigilans** [mindgameSC2/Thought-SC2#1]
In the mini agent's [code](https://github.com/mindgameSC2/mind-SC2/blob/master/mini_agent.py#L354):
```py
def update_population_progress(self):
    for b in self.production_building_list:
        if not b.queue.isEmpty():
            unit = b.queue.first_item()
            unit.progress += self.time_for_one_step
            if unit.progress >= unit.build_time and self.fullfill_food_condition(unit):
                u = b.queue.dequeue()
                if type(u) == type(P.Probe()):
                    self.manage_workers()
                else:
                    self.add_unit(u)
```

It seems that the progress will be updated no matter whether the food has been full, but will be prevented from being created if building progress is finished but food is full.

But isn't the actual behavior to be following?
* If building is progressing, and the food becomes full, the unit will still be created, and the food exceeds its capacity;
* If new building task is to be progressed, but the food is full, then its progress won't be updated.

**Comment by mindgameSC2** [comment]
This should be a bug, we will fix this in a future version.  I will close this issue. If you find your problems not solved, feel free to reopen it.
